export const CHARACTERS_LIST_REQUEST = "CHARACTERS_LIST_REQUEST";
export const CHARACTERS_LIST_SUCCESS = "CHARACTERS_LIST_SUCCESS";
export const CHARACTERS_LIST_FAILURE = "CHARACTERS_LIST_FAILURE";

export const SPECIES_LIST_REQUEST = "SPECIES_LIST_REQUEST";
export const SPECIES_LIST_SUCCESS = "SPECIES_LIST_SUCCESS";
export const SPECIES_LIST_FAILURE = "SPECIES_LIST_FAILURE";

export const STARSHIPS_LIST_REQUEST = "STARSHIPS_LIST_REQUEST";
export const STARSHIPS_LIST_SUCCESS = "STARSHIPS_LIST_SUCCESS";
export const STARSHIPS_LIST_FAILURE = "STARSHIPS_LIST_FAILURE";

export const VEHICLES_LIST_REQUEST = "VEHICLES_LIST_REQUEST";
export const VEHICLES_LIST_SUCCESS = "VEHICLES_LIST_SUCCESS";
export const VEHICLES_LIST_FAILURE = "VEHICLES_LIST_FAILURE";

export const PLANETS_LIST_REQUEST = "PLANETS_LIST_REQUEST";
export const PLANETS_LIST_SUCCESS = "PLANETS_LIST_SUCCESS";
export const PLANETS_LIST_FAILURE = "PLANETS_LIST_FAILURE";

export const FILMS_LIST_REQUEST = "FILMS_LIST_REQUEST";
export const FILMS_LIST_SUCCESS = "FILMS_LIST_SUCCESS";
export const FILMS_LIST_FAILURE = "FILMS_LIST_FAILURE";
